### ISSUE TITLE
Add support for background pushes that set content-available

### ISSUE THREAD

**Issue by buddhisthead** [AvdLee/Poes#12]
This would be similar to the option to generate the mutable content flag.
Within the `aps` section, add `"content-available" : 1`. This should not be included with other keys in the 'aps' section, but can include other data which may also need support for setting.

**Comment by AvdLee** [comment]
@buddhisthead feel free to open a PR! I'm pretty sure it will be an easy one and it would be awesome to have you contributing to the project 💪🏻
